version: 2
jobs:
  build:
    docker:
      - image: alpine:3.10@sha256:acd3ca9941a85e8ed16515bfc5328e4e2f8c128caa72959a58a127b7801ee01f
    steps:
      - checkout
      - run:
          name: build site and push to github-pages
          command: sh publish.sh
    branches:
      only:
        - master
