version: 2
jobs:
  build:
    docker:
      - image: alpine:3.10
    steps:
      - checkout
      - run:
          name: build site and push to github-pages
          command: echo Hello CircleCI
    branches:
      only:
        - master
